
#define DRS2_IS_ALIVE 95
#define DRS2HB 71

#define DRS2_EINFAHRT_FAHRT 60
#define DRS2_EINFAHRT_HALT 61
#define DRS2_AUSFAHRT_FAHRT 62
#define DRS2_AUSFAHRT_HALT 63

#define DRS2_LB_BLOCKED 65
#define DRS2_LB_UNBLOCKED 66
#define DRS2_LB_END_BLOCKED 67
#define DRS2_LB_END_UNBLOCKED 68
#define DRS2_LB_ANF_BLOCKED 69
#define DRS2_LB_ANF_UNBLOCKED 70

#define DRS2_ANF_ENTBLOCKEN 76
#define DRS2_ERL_ENTBLOCKEN 77
#define DRS2_END_ENTBLOCKEN 78

#define DRS2_SIGA_FAHRT 79
#define DRS2_SIGA_HALT 80

#define DRS2_SIGBCD_FAHRT 84
#define DRS2_SIGBCD_HALT 83

#define DRS2_ERSATZA 93
#define DRS2_ERSATZBCD 94

#define DRS2_AUSFAHRT_GESETZT 85
#define DRS2_AUSFAHRT_NICHTGESETZT 86
